# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u0418\u043c\u044f \u043f\u0438\u0442\u043e\u043c\u0446\u0430')),
                ('ptype', models.SmallIntegerField(choices=[(0, '\u041a\u043e\u0442'), (1, '\u0421\u043e\u0431\u0430\u043a\u0430'), (2, '\u0413\u0440\u044b\u0437\u0443\u043d'), (3, '\u041f\u0442\u0438\u0446\u0430')], verbose_name='\u0422\u0438\u043f')),
                ('sex', models.SmallIntegerField(choices=[(0, '\u0414\u0435\u0432\u043e\u0447\u043a\u0430'), (1, '\u041c\u0430\u043b\u044c\u0447\u0438\u043a')], verbose_name='\u041f\u043e\u043b')),
                ('photo', models.FilePathField(path='/home/zhenya/Desktop/sphere/my_proj/shelters/images', recursive=True)),
                ('in_date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f \u0432 \u043f\u0440\u0438\u044e\u0442')),
                ('out_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0432\u0437\u044f\u0442\u0438\u044f \u0438\u0437 \u043f\u0440\u0438\u044e\u0442\u0430')),
                ('owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='\u0425\u043e\u0437\u044f\u0438\u043d')),
            ],
            options={
                'verbose_name': '\u041f\u0438\u0442\u043e\u043c\u0435\u0446',
                'verbose_name_plural': '\u041f\u0438\u0442\u043e\u043c\u0446\u044b',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430')),
                ('comment', models.CharField(max_length=300, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041e\u0446\u0435\u043d\u043a\u0430',
                'verbose_name_plural': '\u041e\u0446\u0435\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0438\u044e\u0442\u0430')),
                ('location', models.CharField(max_length=200, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0438\u044e\u0442',
                'verbose_name_plural': '\u041f\u0440\u0438\u044e\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Volunteer_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('work_time', models.PositiveIntegerField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u0440\u0430\u0431\u043e\u0442\u044b \u0432 \u0447\u0430\u0441\u0430\u0445')),
                ('reward', models.PositiveIntegerField(verbose_name='\u0412\u043e\u0437\u043d\u0430\u0433\u0440\u0430\u0436\u0434\u0435\u043d\u0438\u0435')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.Shelter', verbose_name='\u041f\u0440\u0438\u044e\u0442')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043e\u043b\u043e\u043d\u0442\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043b\u043e\u043d\u0442\u0435\u0440\u0441\u0442\u0432\u043e',
                'verbose_name_plural': '\u0412\u043e\u043b\u043e\u043d\u0442\u0435\u0440\u0441\u0442\u0432\u043e',
            },
        ),
        migrations.AddField(
            model_name='shelter',
            name='volunteers',
            field=models.ManyToManyField(through='shelters.Volunteer_work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.Shelter'),
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.Shelter', verbose_name='\u041f\u0440\u0438\u044e\u0442'),
        ),
    ]
