# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='ptype',
            field=models.SmallIntegerField(choices=[(0, '\u041a\u043e\u0442'), (1, '\u0421\u043e\u0431\u0430\u043a\u0430'), (2, '\u0413\u0440\u044b\u0437\u0443\u043d'), (3, '\u041f\u0442\u0438\u0446\u0430')], db_index=True, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '\u0414\u0435\u0432\u043e\u0447\u043a\u0430'), (1, '\u041c\u0430\u043b\u044c\u0447\u0438\u043a')], db_index=True, verbose_name='\u041f\u043e\u043b'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0438\u044e\u0442\u0430'),
        ),
    ]
